@startuml "Structure of Liquid"
' class LQDraftStore



package Server {
    package Local {
        class LQLocalObjectRepo
        LQUserSetRepo -- LQLocalObjectRepo
        class LQDevelopmentObjectRepo
        class LQDelayMessageDecorator
        LQLocalObjectRepo <|-- LQDevelopmentObjectRepo
        LQDelayMessageDecorator -- LQLocalObjectDummy
        LQDevelopmentObjectRepo -- LQDelayMessageDecorator
        }
    
    package Remote {
        class LQRemoteRepoClient
        class LQRemoteRepoServer
        LQRemoteRepoClient -- LQRemoteRepoServer
        LQRemoteRepoServer -- LQRemoteRepoClient
    }
    interface LQObjectRepo {
        LQObjectDummy at(id, ifAbsent)
        void at(id, ifAbsent, ifPresentPut)
    }
    LQObjectRepo <|-- LQRemoteRepoClient
    LQObjectRepo <|-- LQLocalObjectRepo

    class LQPollRepo {
        default
    }
    LQObjectRepo -- LQPoll
    LQObjectRepo -- LQUserSet
    LQPollRepo -> LQObjectRepo
    
    class LQUserSetRepo {
        default
    }
    LQUserSetRepo -> LQObjectRepo
}

class LQLocalObjectDummy {
    doesNotUnderstand(aMessage)
}
UI -- LQRemoteObjectDummy
LQRemoteRepoClient -- LQRemoteObjectDummy
UI -- LQLocalObjectDummy
LQLocalObjectRepo -- LQLocalObjectDummy
class LQRemoteObjectDummy {
    doesNotUnderstand(aMessage  )
}
LQRemoteObjectDummy -[hidden]- LQLocalObjectDummy

package Core {
  package "Data Structure" {
    class LQPoll  {
        id
        userSetID
        startTime
        isOpen
        void startWithId(id, ifTakenBlock)
    }
    LQPoll "*" <- "1" LQPollDraft
    class LQPollDraft {
        title
    }
    class LQAnswerSet
    LQPoll "1" <- "*" LQAnswerSet
    LQAnswerSet "1" <- "*" LQAnswer
    interface LQAnswer
    class LQAnswer {
        votedChoice
    }
    LQAnswer <|-- LQAnswer

    interface LQQuestion {
        choiceList
    }
    ' I chose * instead of 1 bcLdatastructure is there'
    LQPollDraft "1" <- "*" LQQuestion
    class LQMultiChoiceQuestion  {
        maxNumberOfChoices
    }
    LQQuestion <|-- LQMultiChoiceQuestion
    LQAnswer "*" -- "1" LQQuestion
    class LQChoice {
      description
      excludedGroups
    }
    LQMultiChoiceQuestion "1" -> "*" LQChoice
    class LQUser {
      id
      name
      group
    }
    class LQUserSet {
      id
      title
    }
    LQUserSet "1" -> "*" LQUser
  }

  package Util {
    class LQPollIdGenerator {}
    class LQChoiceProcessor {}
  }
  
  package Passwords {
    class LQPasswordManager{}
    class LQPasswordGuard{}
    LQPoll -- LQPasswordGuard
  }
}

package UI {
    class LQModel
    class LQUserSetMenu {
      openUserSetFileDialog()
      removeSelectedUserSet()
    }
    class LQHostMenu
    class LQUserSetMenu
    LQModel <|-- LQUserSetMenu
    LQModel <|-- LQHostMenu
    class LQStartMenu
    LQModel <|-- LQStartMenu
    LQModel <|-- LQVisualizationControls
    LQModel <|-- LQVisualizationView
    LQVisualizationView -- LQVisualizationControls
    class LQResultsView
    LQModel <|-- LQResultsView
    class LQParticipantMenu {
        sendAnser()
    }
    LQParticipantMenu --|> LQModel
    class LQPollDraftBuilder {
        runPoll()
    }
    class LQMultiChoiceQuestionBuilde{
    
      }
    LQPollDraftBuilder "1" <- "*" LQMultiChoiceQuestionBuilde
    LQPollDraftBuilder --|> LQModel
    LQMultiChoiceQuestionBuilde --|> LQModel

    LQStartMenu -- LQHostMenu
    LQStartMenu -- LQParticipantMenu
    LQHostMenu -- LQResultsView
     LQHostMenu -- LQUserSetMenu
    LQHostMenu -- LQPollDraftBuilder

    class LQUiComponent
    class LQAnswerPanel
    LQAnswerPanel --|> LQUiComponent
    LQParticipantMenu -- LQAnswerPanel

}

@enduml
